# infra/dovecot/dovecot.conf

protocols = imap lmtp

ssl = no

# Pull in modular config files
!include conf.d/10-auth.conf
!include conf.d/10-mail.conf
!include conf.d/10-master.conf

# Logging to stdout so Docker captures it
log_path = /dev/stderr
info_log_path = /dev/stdout