# infra/dovecot/conf.d/10-auth.conf

# Disable plaintext auth over unencrypted connections in production,
# but we allow it here since we're inside a private Docker network
disable_plaintext_auth = no
auth_mechanisms = plain login

# Use LDAP as the authentication backend
!include auth-ldap.conf.ext